### ISSUE TITLE
Fitur Transaksi

### ISSUE THREAD

**Issue by masbrodev** [commitunuja/mpnj-pelapak#7]
Ganti Status Transaksi
Lihat/Detail Transaksi
Kofirmasi Transaksi

**Comment by masbrodev** [comment]
#22

**Comment by masbrodev** [comment]
Done

**Comment by milhamsuryapratama** [comment]
maaf @masbrodev, issue ini saya re-open karena mau saya custom

**Comment by milhamsuryapratama** [comment]
![image](https://user-images.githubusercontent.com/46917596/81425001-fe821200-9180-11ea-9393-9df44a95ac9e.png)

ijin custoom jadi kayak gitu lead @masbrodev
